version: "3.3"
services:
  db:
    image: postgres:11.11
    volumes:
      - "../tmpapp/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: asdfgh
    ports:
    - 5432:5432
  prueba_hoy:
    build:
      context: "./prueba/."
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - 8081:8081
    volumes:
      - "./prueba:/app"
    environment:
      RAILS_ENV: development
    command: 'bundle exec rails s --binding=0.0.0.0 -p8081'
    network_mode: "host"
