FROM ruby:2.7-alpine
RUN gem install bundler -v 2.3.19
RUN apk add --no-cache build-base postgresql-client postgresql-dev bash libcurl



RUN mkdir /app
RUN mkdir /app/log/
WORKDIR /app

COPY Gemfile /app/Gemfile
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

RUN bundle
RUN bundle install

COPY . /app

ENTRYPOINT ["entrypoint.sh"]
EXPOSE 8081
CMD bundle exec rails s -b 0.0.0.0 -p8081
